Fixed "No such process" error process_monitor_unix
OSError: [Error 3] No such process thrown on line 91 when restarting a process. Specifically when the process has already crashed due to a fuzzing test case. Added a try-catch statement to see if pid exists.